### ISSUE TITLE
Xlib.error.DisplayNameError: Bad display name ""

### ISSUE THREAD

**Issue by chrisdfennell** [fjpereny/wowzer#8]
Hello!

I am getting the following error when trying to run this in python.  Any insights?

Starting computer vision screen update...
Exception in thread update screen thread:
Traceback (most recent call last):
  File "C:\Users\Infan\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Infan\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Infan\Desktop\wowzer-main\src\main.py", line 30, in update_screen
    dsp = display.Display()
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Infan\AppData\Local\Programs\Python\Python312\Lib\site-packages\Xlib\display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Infan\AppData\Local\Programs\Python\Python312\Lib\site-packages\Xlib\display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "C:\Users\Infan\AppData\Local\Programs\Python\Python312\Lib\site-packages\Xlib\protocol\display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Infan\AppData\Local\Programs\Python\Python312\Lib\site-packages\Xlib\support\connect.py", line 73, in get_display
    return mod.get_display(display)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Infan\AppData\Local\Programs\Python\Python312\Lib\site-packages\Xlib\support\unix_connect.py", line 59, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""

**Comment by fjpereny** [comment]
Are you on windows?  When I developed this I was using linux which Mac / Linux machines use X server.  You will just need to remove the X library and calls.

**Comment by gavr1** [comment]
@fjpereny I have the same issue on Macbook pro M1. Even after instalation of py-xlib it wasn't work. Seems like this lib can't recognize my display. Could you recommend any solutions please?
